type SqliteLike = { exec: (sql: string) => unknown };

const STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'STAFF',
    active INTEGER NOT NULL DEFAULT 1,
    last_login_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    token TEXT NOT NULL UNIQUE,
    user_id TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    ip TEXT,
    user_agent TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id)`,
  `CREATE TABLE IF NOT EXISTS settings (
    id TEXT PRIMARY KEY,
    payload TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS hotels (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    city TEXT NOT NULL,
    star_rating INTEGER NOT NULL DEFAULT 5,
    distance_to_haram TEXT,
    contact_person TEXT,
    contact_phone TEXT,
    default_cost_sar REAL NOT NULL DEFAULT 0,
    default_sell_sar REAL NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS customers (
    id TEXT PRIMARY KEY,
    booking_type TEXT NOT NULL DEFAULT 'Private',
    name TEXT NOT NULL,
    travel_company TEXT,
    phone TEXT NOT NULL DEFAULT '',
    email TEXT,
    passport TEXT,
    country TEXT,
    last_booking_ref TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS vendors (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    pic TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT '',
    email TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Other',
    unit TEXT NOT NULL DEFAULT 'unit',
    default_cost_sar REAL NOT NULL DEFAULT 0,
    default_sell_sar REAL NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS hotel_bookings (
    id TEXT PRIMARY KEY,
    booking_ref TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'Draft',
    staff_name TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL DEFAULT 'manual',
    visa_action TEXT,
    booking_type TEXT NOT NULL DEFAULT 'Private',
    travel_company TEXT,
    vendor_name TEXT,
    vendor_pic TEXT,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL DEFAULT '',
    customer_email TEXT NOT NULL DEFAULT '',
    customer_passport TEXT NOT NULL DEFAULT '',
    customer_country TEXT NOT NULL DEFAULT 'Indonesia',
    adults INTEGER NOT NULL DEFAULT 0,
    children INTEGER NOT NULL DEFAULT 0,
    infants INTEGER NOT NULL DEFAULT 0,
    notes TEXT,
    hotel_name TEXT NOT NULL,
    hotel_city TEXT NOT NULL,
    star_rating INTEGER NOT NULL DEFAULT 5,
    check_in_date TEXT NOT NULL,
    check_out_date TEXT NOT NULL,
    total_nights INTEGER NOT NULL DEFAULT 1,
    hcn_rsvp TEXT,
    hotel_transfer_json TEXT,
    import_source_json TEXT,
    input_currency TEXT NOT NULL DEFAULT 'SAR',
    exchange_rate REAL NOT NULL DEFAULT 4250,
    total_cost_sar REAL NOT NULL DEFAULT 0,
    total_sell_sar REAL NOT NULL DEFAULT 0,
    total_cost_idr REAL NOT NULL DEFAULT 0,
    total_sell_idr REAL NOT NULL DEFAULT 0,
    profit_sar REAL NOT NULL DEFAULT 0,
    profit_idr REAL NOT NULL DEFAULT 0,
    profit_margin_percent REAL NOT NULL DEFAULT 0,
    amount_paid_sar REAL NOT NULL DEFAULT 0,
    amount_paid_idr REAL NOT NULL DEFAULT 0,
    payment_exchange_rate REAL,
    payment_method TEXT NOT NULL DEFAULT 'Bank Transfer (BCA/Mandiri)',
    due_date TEXT NOT NULL DEFAULT '',
    payment_reference TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_hotel_status ON hotel_bookings(status)`,
  `CREATE INDEX IF NOT EXISTS idx_hotel_checkin ON hotel_bookings(check_in_date)`,
  `CREATE TABLE IF NOT EXISTS booking_rooms (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL,
    room_type TEXT NOT NULL,
    number_of_rooms INTEGER NOT NULL DEFAULT 1,
    cost_per_night REAL NOT NULL DEFAULT 0,
    sell_per_night REAL NOT NULL DEFAULT 0,
    meal_plan TEXT NOT NULL DEFAULT 'Breakfast',
    sort_order INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (booking_id) REFERENCES hotel_bookings(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS booking_services (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL,
    description TEXT NOT NULL,
    cost REAL NOT NULL DEFAULT 0,
    sell REAL NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (booking_id) REFERENCES hotel_bookings(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS hotel_payments (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL,
    paid_at TEXT NOT NULL,
    amount_sar REAL NOT NULL DEFAULT 0,
    amount_idr REAL NOT NULL DEFAULT 0,
    exchange_rate REAL,
    direction TEXT NOT NULL DEFAULT 'customer',
    method TEXT NOT NULL DEFAULT 'Bank Transfer (BCA/Mandiri)',
    reference TEXT,
    note TEXT,
    FOREIGN KEY (booking_id) REFERENCES hotel_bookings(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS train_bookings (
    id TEXT PRIMARY KEY,
    train_ref TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'Draft',
    staff_name TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL DEFAULT 'manual',
    booking_type TEXT NOT NULL DEFAULT 'Private',
    customer_name TEXT NOT NULL,
    travel_company TEXT,
    customer_phone TEXT NOT NULL DEFAULT '',
    customer_email TEXT NOT NULL DEFAULT '',
    customer_country TEXT NOT NULL DEFAULT 'Indonesia',
    notes TEXT,
    trip_type TEXT NOT NULL DEFAULT 'One-Way',
    origin_code TEXT NOT NULL,
    destination_code TEXT NOT NULL,
    train_class TEXT NOT NULL DEFAULT 'Economy',
    vendor_name TEXT,
    vendor_pic TEXT,
    input_currency TEXT NOT NULL DEFAULT 'SAR',
    exchange_rate REAL NOT NULL DEFAULT 4250,
    cost_per_pax REAL NOT NULL DEFAULT 0,
    sell_per_pax REAL NOT NULL DEFAULT 0,
    pax_count INTEGER NOT NULL DEFAULT 0,
    total_cost_sar REAL NOT NULL DEFAULT 0,
    total_sell_sar REAL NOT NULL DEFAULT 0,
    total_cost_idr REAL NOT NULL DEFAULT 0,
    total_sell_idr REAL NOT NULL DEFAULT 0,
    profit_sar REAL NOT NULL DEFAULT 0,
    profit_idr REAL NOT NULL DEFAULT 0,
    profit_margin_percent REAL NOT NULL DEFAULT 0,
    amount_paid_sar REAL NOT NULL DEFAULT 0,
    amount_paid_idr REAL NOT NULL DEFAULT 0,
    payment_exchange_rate REAL,
    payment_method TEXT NOT NULL DEFAULT 'Bank Transfer (BCA/Mandiri)',
    due_date TEXT NOT NULL DEFAULT '',
    payment_reference TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS train_legs (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL,
    direction TEXT NOT NULL,
    train_no TEXT NOT NULL DEFAULT '',
    departure_date TEXT NOT NULL,
    departure_time TEXT NOT NULL DEFAULT '00:00',
    arrival_date TEXT NOT NULL,
    arrival_time TEXT NOT NULL DEFAULT '',
    duration_minutes INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (booking_id) REFERENCES train_bookings(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS train_passengers (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL,
    full_name TEXT NOT NULL,
    id_number TEXT NOT NULL DEFAULT '',
    nationality TEXT NOT NULL DEFAULT 'Indonesia',
    category TEXT NOT NULL DEFAULT 'Adult',
    seat_coach TEXT NOT NULL DEFAULT '',
    seat_number TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (booking_id) REFERENCES train_bookings(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS train_extras (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL,
    description TEXT NOT NULL,
    cost REAL NOT NULL DEFAULT 0,
    sell REAL NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (booking_id) REFERENCES train_bookings(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS train_payments (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL,
    paid_at TEXT NOT NULL,
    amount_sar REAL NOT NULL DEFAULT 0,
    amount_idr REAL NOT NULL DEFAULT 0,
    exchange_rate REAL NOT NULL DEFAULT 4250,
    method TEXT NOT NULL DEFAULT 'Bank Transfer (BCA/Mandiri)',
    reference TEXT,
    note TEXT,
    FOREIGN KEY (booking_id) REFERENCES train_bookings(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS armada_bookings (
    id TEXT PRIMARY KEY,
    armada_ref TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'Draft',
    staff_name TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL DEFAULT 'manual',
    booking_type TEXT NOT NULL DEFAULT 'Group',
    customer_name TEXT NOT NULL,
    travel_company TEXT,
    customer_phone TEXT NOT NULL DEFAULT '',
    customer_email TEXT NOT NULL DEFAULT '',
    customer_country TEXT NOT NULL DEFAULT 'Indonesia',
    group_size INTEGER NOT NULL DEFAULT 0,
    notes TEXT,
    service_type TEXT NOT NULL DEFAULT 'One-Way',
    origin_code TEXT NOT NULL,
    destination_code TEXT NOT NULL,
    vehicle_type TEXT NOT NULL,
    vendor_name TEXT,
    vendor_pic TEXT,
    input_currency TEXT NOT NULL DEFAULT 'SAR',
    exchange_rate REAL NOT NULL DEFAULT 4250,
    cost_per_unit REAL NOT NULL DEFAULT 0,
    sell_per_unit REAL NOT NULL DEFAULT 0,
    unit_count INTEGER NOT NULL DEFAULT 0,
    total_seats INTEGER NOT NULL DEFAULT 0,
    total_cost_sar REAL NOT NULL DEFAULT 0,
    total_sell_sar REAL NOT NULL DEFAULT 0,
    total_cost_idr REAL NOT NULL DEFAULT 0,
    total_sell_idr REAL NOT NULL DEFAULT 0,
    profit_sar REAL NOT NULL DEFAULT 0,
    profit_idr REAL NOT NULL DEFAULT 0,
    profit_margin_percent REAL NOT NULL DEFAULT 0,
    amount_paid_sar REAL NOT NULL DEFAULT 0,
    amount_paid_idr REAL NOT NULL DEFAULT 0,
    payment_exchange_rate REAL,
    payment_method TEXT NOT NULL DEFAULT 'Bank Transfer (BCA/Mandiri)',
    due_date TEXT NOT NULL DEFAULT '',
    payment_reference TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS armada_legs (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL,
    direction TEXT NOT NULL,
    route_label TEXT NOT NULL DEFAULT '',
    departure_date TEXT NOT NULL,
    departure_time TEXT NOT NULL DEFAULT '00:00',
    arrival_date TEXT NOT NULL,
    arrival_time TEXT NOT NULL DEFAULT '',
    duration_minutes INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (booking_id) REFERENCES armada_bookings(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS armada_units (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL,
    vehicle_type TEXT NOT NULL,
    plate_number TEXT NOT NULL DEFAULT '',
    driver_name TEXT NOT NULL DEFAULT '',
    driver_phone TEXT NOT NULL DEFAULT '',
    capacity INTEGER NOT NULL DEFAULT 0,
    note TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (booking_id) REFERENCES armada_bookings(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS armada_extras (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL,
    description TEXT NOT NULL,
    cost REAL NOT NULL DEFAULT 0,
    sell REAL NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (booking_id) REFERENCES armada_bookings(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS armada_payments (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL,
    paid_at TEXT NOT NULL,
    amount_sar REAL NOT NULL DEFAULT 0,
    amount_idr REAL NOT NULL DEFAULT 0,
    exchange_rate REAL NOT NULL DEFAULT 4250,
    method TEXT NOT NULL DEFAULT 'Bank Transfer (BCA/Mandiri)',
    reference TEXT,
    note TEXT,
    FOREIGN KEY (booking_id) REFERENCES armada_bookings(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS audit_logs (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    user_email TEXT,
    action TEXT NOT NULL,
    entity TEXT NOT NULL,
    entity_id TEXT,
    details TEXT,
    ip TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at)`,
  `CREATE TABLE IF NOT EXISTS exchange_rates (
    id TEXT PRIMARY KEY,
    rate REAL NOT NULL,
    source TEXT NOT NULL,
    stale INTEGER NOT NULL DEFAULT 1,
    updated_at TEXT NOT NULL
  )`,
];

export function migrate(db: SqliteLike) {
  db.exec('BEGIN');
  try {
    for (const sql of STATEMENTS) db.exec(sql);
    db.exec('COMMIT');
  } catch (err) {
    db.exec('ROLLBACK');
    throw err;
  }
}
